# Change all occurrences of "sample_validator" to your prerferred name
services:
  allora_node:
    container_name: allora_node
    image: "alloranetwork/allora-chain:v0.3.0"
    environment:
      - NETWORK=allora-testnet-1
      - MONIKER=Nodium
      - APP_HOME=/data
      - HOME=/data
      - STATE_SYNC_RPC1=https://allora-rpc.testnet-1.testnet.allora.network:443
      - STATE_SYNC_RPC2=https://allora-rpc.testnet-1.testnet.allora.network:443
    volumes:
      - ./data_validator:/data
      - ./scripts/:/scripts
    ports:
      - "26656-26657:26656-26657"
    user: "0:0"
    entrypoint: /scripts/l1_node.sh
